### ISSUE TITLE
Springfiles doesn't know about mods released after repo split

### ISSUE THREAD

**Issue by db81** [springfiles/upq#41]
The versions http://api.springfiles.com and the XMLRPC interface give you for zk:stable, evo:stable, swiw:stable are outdated. It doesn't know about techa:stable and jauria:stable at all.

The latest zk stable known to springfiles is 1.2.6.18 and that's also the oldest version in zk.repo.springrts.com/versions.gz. The latest evo stable known to springfiles is 7.63 and the oldest stable in zk.repo.springrts.com/versions.gz is 7.64. Same goes for imperial winter.

It appears that split repos are not handled properly.

**Comment by abma** [comment]
@gajop:

rapid support is partly implemented:

required change would be:

- create table/data structure for rapid
- insert rapid to table when fetched
- change search, so it supports the new table and returns path to streamer + sdp hash

**Comment by abma** [comment]
i've removed the tags from upq, so no broken redundancy any more.
