### ISSUE TITLE
not valid json from exampleclient.py

### ISSUE THREAD

**Issue by TurBoss** [springfiles/upq#43]
i'm trying to parse the output from exampleclient.py but json seems not valid not sure...
<pre>'timestamp': >DateTime '20150116T05:09:36' at 7f4746868170>,</pre>

the > was intentionally turned

**Comment by abma** [comment]
the example client uses xmlrpc. upq offers xmlrpc and a json api.

also the exampleclient just dumps the python datetime object, the console output is nothing you should use.

i guess that is what you want:

**Comment by abma** [comment]
imo nothing to fix, also idk where/what to improve with the docs, need more specific info to do so.
