### ISSUE TITLE
The map Random Crags 0.6 is unexplainably gone from api listing

### ISSUE THREAD

**Issue by Anarchid** [springfiles/upq#54]
The map Random Crags 0.6 is unexplainably gone from api listing. This is a new situation; it was listed and served for quite some time.

Map is listed and downloadable on SF web: https://springfiles.com/spring/spring-maps/random-crags-4
Map is downloable directly through a crafted link: http://api.springfiles.com/files/maps/random_crags_v0.6.sd7
Map is __not__ listed via api.springfiles.com (other versions of Random Crags, however, are): http://api.springfiles.com/?springname=&filename=random_crags_v0*&tag=&sdp=&category=map

This in turn propagates to zero-k.info and results in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2629

**Comment by Aquanim** [comment]
I uploaded a Random Crags v0.61 with nothing changed beyond the version number and it appears to be downloadable at this time.

**Comment by abma** [comment]
oooops, i missed this one. was fixed some time ago
