### ISSUE TITLE
Different maps with same base name show merged history

### ISSUE THREAD

**Issue by esainane** [springfiles/upq#55]
I apologize if this isn't the correct project to post an issue on! I've had a look at the repositories under springfiles and couldn't find any that seemed to exactly correspond to the main site, but this seemed to be the most relevant?

About a week after I uploaded Hourglass v0.1 at https://springfiles.com/spring/spring-maps/hourglass someone uploaded a different map called Hourglass v1.0 at https://springfiles.com/spring/spring-maps/hourglass-0

These maps are unrelated aside from having the same name, and do seem to be internally disambiguated by giving the latter upload a url suffixed with -0. In the top right, however, the "Version History" box includes links to both maps, on both pages.

I'm not sure if springfiles has a policy for name conflicts, and I couldn't find a contact page. A search showed up https://springfiles.com/contact , but the page is currently a 404.

It would be nice if there was a way to separate version histories for unrelated maps. Perhaps the URL id could be used?

**Comment by abma** [comment]
atm there is no naming policy at springfiles, sorry.
