### ISSUE TITLE
New files don't show up in Api 

### ISSUE THREAD

**Issue by icexuick** [springfiles/upq#62]
Newly uploaded maps to springfiles don't show up in the api.
I've uploaded (and tried updating) multiple files, but they don't show up.
Last upload/file was from 202-10-29.

**Comment by icexuick** [comment]
This still is down. Can someone respond if this has been noticed/planned to fix?

**Comment by icexuick** [comment]
Any headsup when this might be working again? We're working on multiple new maps, but with them showing up in the api or not being able to update version numbers, this is not possible.

**Comment by icexuick** [comment]
It's been pretty quiet now for some time.
I hope someone can pick this up / fix it.
We can't deliver/upload or update new maps now for more than 3 weeks.

**Comment by abma** [comment]
damn, i missed your bug report. sorry.

should work again, the cron job wasn't run.

**Comment by icexuick** [comment]
Awesome! API shows it now!
Many many thanks.

Last question: I still can't seem to update the version number by editing the map.
Any idea how this could be fixed?

**Comment by abma** [comment]
this comes to the point of rewriting how uploading works:

https://github.com/spring/upq/issues/58

current springfiles uses drupal 6 which is EOL since a very long time, so changing/fixing there stuff is a waste of time.

sorry..

**Comment by icexuick** [comment]
So doing (many) version upgrades now needs just a completely new "map" item.
too bad, it worked very well - but well the API is more important to get maps to work/download.
Thanks for checking/replying! <3
